package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setCaption(String caption) {
		set("caption", caption);
		return (M)this;
	}
	
	public String getCaption() {
		return getStr("caption");
	}

	public M setImage(String image) {
		set("image", image);
		return (M)this;
	}
	
	public String getImage() {
		return getStr("image");
	}

	public M setIntroduction(String introduction) {
		set("introduction", introduction);
		return (M)this;
	}
	
	public String getIntroduction() {
		return getStr("introduction");
	}

	public M setHits(Long hits) {
		set("hits", hits);
		return (M)this;
	}
	
	public Long getHits() {
		return getLong("hits");
	}

	public M setProductCategoryId(Long productCategoryId) {
		set("productCategoryId", productCategoryId);
		return (M)this;
	}
	
	public Long getProductCategoryId() {
		return getLong("productCategoryId");
	}

	public M setParameterValue(String parameterValue) {
		set("parameterValue", parameterValue);
		return (M)this;
	}
	
	public String getParameterValue() {
		return getStr("parameterValue");
	}

	public M setSpecifications(String specifications) {
		set("specifications", specifications);
		return (M)this;
	}
	
	public String getSpecifications() {
		return getStr("specifications");
	}

	public M setMemo(String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public String getMemo() {
		return getStr("memo");
	}

	public M setSn(String sn) {
		set("sn", sn);
		return (M)this;
	}
	
	public String getSn() {
		return getStr("sn");
	}

	public M setWeight(String weight) {
		set("weight", weight);
		return (M)this;
	}
	
	public String getWeight() {
		return getStr("weight");
	}

	public M setProduction(String production) {
		set("production", production);
		return (M)this;
	}
	
	public String getProduction() {
		return getStr("production");
	}

	public M setSales(Long sales) {
		set("sales", sales);
		return (M)this;
	}
	
	public Long getSales() {
		return getLong("sales");
	}

	public M setIsMarketable(Boolean isMarketable) {
		set("isMarketable", isMarketable);
		return (M)this;
	}
	
	public Boolean getIsMarketable() {
		return get("isMarketable");
	}

	public M setUnit(String unit) {
		set("unit", unit);
		return (M)this;
	}
	
	public String getUnit() {
		return getStr("unit");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setCost(java.math.BigDecimal cost) {
		set("cost", cost);
		return (M)this;
	}
	
	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("marketPrice", marketPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getMarketPrice() {
		return get("marketPrice");
	}

	public M setProductImage(String productImage) {
		set("productImage", productImage);
		return (M)this;
	}
	
	public String getProductImage() {
		return getStr("productImage");
	}

	public M setProductOrigin(String productOrigin) {
		set("productOrigin", productOrigin);
		return (M)this;
	}
	
	public String getProductOrigin() {
		return getStr("productOrigin");
	}

	public M setByProductData(String byProductData) {
		set("byProductData", byProductData);
		return (M)this;
	}
	
	public String getByProductData() {
		return getStr("byProductData");
	}

	public M setByProductDetailData(String byProductDetailData) {
		set("byProductDetailData", byProductDetailData);
		return (M)this;
	}
	
	public String getByProductDetailData() {
		return getStr("byProductDetailData");
	}

	public M setByImages(String byImages) {
		set("byImages", byImages);
		return (M)this;
	}
	
	public String getByImages() {
		return getStr("byImages");
	}

	public M setTrait(String trait) {
		set("trait", trait);
		return (M)this;
	}
	
	public String getTrait() {
		return getStr("trait");
	}

	public M setSpecList(String specList) {
		set("specList", specList);
		return (M)this;
	}
	
	public String getSpecList() {
		return getStr("specList");
	}

	public M setDescriptionList(String descriptionList) {
		set("descriptionList", descriptionList);
		return (M)this;
	}
	
	public String getDescriptionList() {
		return getStr("descriptionList");
	}

}
