package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCtcMember<M extends BaseCtcMember<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setSort(Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public Integer getSort() {
		return getInt("sort");
	}

	public M setIsEnabled(Boolean isEnabled) {
		set("isEnabled", isEnabled);
		return (M)this;
	}
	
	public Boolean getIsEnabled() {
		return get("isEnabled");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}
	
	public String getContent() {
		return getStr("content");
	}

	public M setImage(String image) {
		set("image", image);
		return (M)this;
	}
	
	public String getImage() {
		return getStr("image");
	}

	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}
	
	public String getType() {
		return getStr("type");
	}

	public M setExpireDays(Integer expireDays) {
		set("expireDays", expireDays);
		return (M)this;
	}
	
	public Integer getExpireDays() {
		return getInt("expireDays");
	}

}
