package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCtcUserMember<M extends BaseCtcUserMember<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setUserId(Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public Long getUserId() {
		return getLong("userId");
	}

	public M setCtcMemberId(Long ctcMemberId) {
		set("ctcMemberId", ctcMemberId);
		return (M)this;
	}
	
	public Long getCtcMemberId() {
		return getLong("ctcMemberId");
	}

	public M setExpireDayte(java.util.Date expireDayte) {
		set("expireDayte", expireDayte);
		return (M)this;
	}
	
	public java.util.Date getExpireDayte() {
		return get("expireDayte");
	}


	public M setDestruction(Boolean destruction) {
		set("destruction", destruction);
		return (M)this;
	}

	public Boolean getDestruction() {
		return get("destruction");
	}

}
