package com.cms.entity;

import com.cms.entity.base.BaseCtcUserMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CtcUserMember extends BaseCtcUserMember<CtcUserMember> {
	public static final CtcUserMember dao = new CtcUserMember().dao();
}
